# Generated by Django 2.2.13 on 2023-02-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='identity_number',
            new_name='email',
        ),
    ]
