# Generated by Django 2.2.4 on 2023-02-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0002_auto_20230131_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_level',
            field=models.ManyToManyField(related_name='members', to='group_project.userLevel'),
        ),
    ]
