# Generated by Django 2.2.4 on 2023-02-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0005_auto_20230201_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_level',
            field=models.ManyToManyField(default=2, related_name='members', to='group_project.userLevel'),
        ),
    ]
