# Generated by Django 2.2.4 on 2023-02-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0006_auto_20230201_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='user_level',
            field=models.ManyToManyField(related_name='members', to='group_project.userLevel'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
