# Generated by Django 2.2.4 on 2023-02-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0007_auto_20230201_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('identity_number', models.IntegerField()),
                ('mobile_num', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('problem_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='group_project.members')),
            ],
        ),
    ]
