# Generated by Django 2.2.4 on 2023-02-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0008_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('identity_number', models.IntegerField(unique=True)),
                ('mobile_num', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
